[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = ['@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/', '@solmate=lib/solmate/src/']


# eth_rpc_url="https://eth-sepolia.g.alchemy.com/v2/phKZlw4nyzHsPKHrOIx-jfaHvvl4zFPS"
# etherscan_api_key='$(ETHERSCAN_API)'
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
